### ISSUE TITLE
src/ra_server_proc.erl: illegal pattern

### ISSUE THREAD

**Issue by dmarinuswoodwing** [rabbitmq/ra#101]
While building using erlang 10 I get the following compilation error:
```
 ERLC   ra_server.erl ra_server_proc.erl
src/ra_server_proc.erl:896: illegal pattern
src/ra_server_proc.erl:899: variable 'S' is unbound
src/ra_server_proc.erl:900: illegal pattern
src/ra_server_proc.erl:905: variable 'E' is unbound
src/ra_server_proc.erl:905: variable 'S' is unbound
erlang.mk:5176: recipe for target 'ebin/ra.app' failed
make[1]: *** [ebin/ra.app] Error 1
erlang.mk:4967: recipe for target 'app' failed
make: *** [app] Error 2
```
I've bisected this to this commit: https://github.com/rabbitmq/ra/commit/16f2c781aa653b62383964aafbac2f1ada3f33d8#diff-13c9f530c6a97d06b3b6f4a51144a8faR896

**Comment by michaelklishin** [comment]
You may have noticed that the commit is from Nov 2018. So how likely is it that Ra hasn't compiled the entire time? Not very likely.

You are using an unsupported Erlang version. Ra requires OTP 21.3, which provides new syntax for stack trace extraction.
